on:
  push:
    branches:
      main

name: Render-Book-from-main

jobs:

  bookdown:

    name: Render-Book

    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    if: "!(contains(github.event.head_commit.message, 'ci skip')||contains(github.event.head_commit.message, 'skip ci'))"
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache DESC dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-

      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Render Book html
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")'

        #- name: Render Book pdf
        #run: Rscript -e 'bookdown::render_book("index.Rmd", new_session = FALSE, output_format = "bookdown::pdf_book")'

      - name: Commit results
        run: |
          cp -r favicon/ docs/
          cd docs
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name "gh-pages committer"
          git init
          git add .
          git commit -m 'update book'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:gh-pages --force
