on: pull_request

name: PR-workflow

jobs:

  bookdown:

    name: Render Book

    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    if: github.repository == 'ropensci/statistical-software-review-book'
    steps:

      - name: Is this a fork
        run: |
          fork=$(jq --raw-output .pull_request.head.repo.fork "${GITHUB_EVENT_PATH}");echo "fork=${fork}" >> $GITHUB_ENV
          if [ $fork == 'false' ]
          then
            echo "This is not a fork, we shall deploy a preview."
          else
            echo "This is a fork, we shall not deploy a preview."
          fi

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book html
        run: Rscript -e 'quarto::quarto_render(output_format = "html")'

          #- name: Render book PDF
          #run: Rscript -e 'quarto::quarto_render(output_format = "pdf")'

          #- name: Move files around
          #run: Rscript -e 'file.copy(from = "pdfbook/ropensci-statistical-software-review-book.pdf", to = "_book/ropensci-statistical-software-review-book.pdf")' -e 'purrr::walk(list.files("images", full.names = TRUE), file.copy, to = "_book/images")'

      - uses: actions/setup-node@v1

      - name: Deploy to Netlify
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './_book'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          # these all default to 'true'
          enable-pull-request-comment: false
          enable-commit-comment: false
          # enable-commit-status: true
          #o verwrites-pull-request-comment: true
        timeout-minutes: 1
